rules:
  indentation: 0
    # - 2
    # -
      # size: 2
  empty-line-between-blocks: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  placeholder-in-extend: 0
  no-color-literals: 0
  class-name-format:
    - 1
    -
      convention: 'hyphenatedbem'
  variable-name-format:
    - 1
    -
      convention: 'hyphenatedbem'
  property-sort-order:
    - 1
    -
      order: 'smacss'
