config:
  backup: true
  banner: true
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  ignore_missing_in_dotdrop: true
  minversion: 0.29.4
  instignore:
    - '*/__pycache__/*'
  filter_file:
    - ./dotdrop_filters.py

actions:
  pre:
    oh_my_zsh_install: test -e ~/.oh-my-zsh/oh-my-zsh.sh || (rm -rf ~/.oh-my-zsh; sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)")
    check_interception_vimproved: test -e /opt/interception-vimproved/interception-vimproved
  nvim_plug_install: nvim +PlugInstall +qall
  update_crontab: '(echo "# vim: nomodifiable"; echo "# Managed by dotdrop"; cat /tmp/dotdrop-crontab) | crontab -'

  post:
    pacman_check_requirements: echo "Missing packages:" && bash -c "comm -23 <(sort -u {{@@ _dotfile_abs_src @@}}) <(pacman -Qq | sort)"

variables:
  gtk_theme: 'vimix-doder'
  gtk_icon_theme: 'Papirus'
  gtk_cursor_theme: 'breeze_cursors'
  color_background: '181e24'
  color_foreground: 'FFFFFD'
  color_text: '000000'
  color_cursor: 'ffffff'
  color_normal_black: '0d141a'
  color_normal_red: 'ad4117'
  color_normal_green: '659b45'
  color_normal_yellow: 'b8cc4b'
  color_normal_blue: '3a74bc'
  color_normal_magenta: 'bdcb92'
  color_normal_cyan: '96744A'
  color_normal_white: 'e3e2e1'
  color_bright_black: '5b7083'
  color_bright_red: 'f6f2b9'
  color_bright_green: '8d9fba'
  color_bright_yellow: '7fd84b'
  color_bright_blue: 'e6c675'
  color_bright_magenta: 'e7ff5f'
  color_bright_cyan: 'd19851'
  color_bright_white: 'fffffd'
  color_dim_black: '333333'
  color_dim_red: 'f2777a'
  color_dim_green: '99cc99'
  color_dim_yellow: 'ffcc66'
  color_dim_blue: '6699cc'
  color_dim_magenta: 'cc99cc'
  color_dim_cyan: '66cccc'
  color_dim_white: 'dddddd'

  standard_ignored_folders:
    - '.git'
    - '.pioenvs'
    - '.piolibdeps'
    - '.pio'
    - 'env'
    - 'venv'
    - 'build'
    - 'dist'
    - 'public'
    - 'static'
    - 'vendor'
    - 'htmlcov'
    - 'node_modules'
    - '__pycache__'
    - 'jest-coverage'
    - 'static'
    - 'static.debug'
    - 'migrations'
    - 'typings'

  standard_ignored_files:
    - '*-blx.bib'
    - '*.aux'
    - '*.blg'
    - '*.bbl'
    - '*.bcf'
    - '*.cut'
    - '*.fdb_latexmk'
    - '*.fls'
    - '*.log'
    - '*.nav'
    - '*.out'
    - '*.pdf'
    - '*.run.xml'
    - '*.slx'
    - '*.slxc'
    - '*.snm'
    - '*.swp'
    - '*.synctex(busy)'
    - '*.synctex.gz'
    - '*.toc'
    - '*.xdv'
    - '*.zip'
    - 'package-lock.json'
    - 'tags*'
    - 'yarn.*'

dynvariables:
  mozilla_path: find ~/.mozilla/firefox -maxdepth 1 -name '*.default*' -and -not -name '*.bak' || true
  cura_version: cura --version 2>/dev/null | sed 's/.*\([0-9]\+\.[0-9]\+\)\.[0-9]\+/\1/'
  # Use a dynamic variable as a path and populate it with crontab
  # Hack to make compare work correctly
  populate_crontab: crontab -l > /tmp/dotdrop-crontab; echo /tmp/dotdrop-crontab
  contacts: test -e ~/.config/dunst/contacts/contacts-list.txt && cat ~/.config/dunst/contacts/contacts-list.txt || true
trans_read:
  _gpg: test {0} -nt {{@@ _dotfile_abs_dst @@}} && (
    gpg2 -q --for-your-eyes-only --no-tty --decrypt {0} > {1}) || (
    cat {{@@ _dotfile_abs_dst @@}} > {1})

trans_write:
  _gpg: gpg2 --no-tty --encrypt -r "$(gpg2 --list-packets {{@@ _dotfile_abs_src @@}} 2>/dev/null | awk 'NR == 2 {{ print $9 }}')" < {0} > {1}

dotfiles:
  alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    src: ./alacritty/alacritty.yml

  autorandr:
    dst: ~/.config/autorandr/postswitch
    src: ./autorandr/postswitch
    link: link

  bin:
    dst: ~/.local/bin/
    src: ./bin/

  picom:
    dst: ~/.config/picom/picom.conf
    src: ./picom/picom.conf
    link: link

  check_pacman_packages:
    dst:
    src: ./pacman-package-list.txt
    actions:
      - pacman_check_requirements

  chktex:
    dst: ~/.chktexrc
    src: ./chktex/.chktexrc
    link: link

  ctags:
    dst: ~/.ctags
    src: ./ctags/.ctags
    link: link

  cron:
    # Use a dynamic variable as a path and populate it with crontab
    # Hack to make compare work correctly
    dst: "{{@@ populate_crontab @@}}"
    src: ./cron/crontab
    actions:
      - update_crontab

  cura:
    dst: "~/.config/cura/{{@@ cura_version @@}}/cura.cfg"
    src: ./cura/cura.cfg

  cura_machines:
    dst: "~/.local/share/cura/{{@@ cura_version @@}}/"
    src: ./cura_machines
    # link: link_children

  dunst:
    dst: ~/.config/dunst
    src: ./dunst

  etc:
    dst: /etc/
    src: ./etc/

  firefox:
    dst: '{{@@ mozilla_path @@}}'
    src: ./firefox/
    chmod: 700

  flake8:
    dst: ~/.config/flake8
    src: ./flake8/flake8
    link: link

  fontconfig:
    src: ./fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
    link: link

  git:
    dst: ~/.config/git/
    src: ./git/
    link: link

  gtk:
    dst: ~/.config/gtk-3.0/
    src: ./gtk/

  interception:
    dst: /etc/interception/
    src: ./interception
    actions:
      - check_interception_vimproved

  latex_templates:
    dst: ~/.local/templates/latex
    src: ./latex_templates/

  linters:
    dst: ~/
    src: ./linters/
    link: link_children

  mpd:
    dst: ~/.config/mpd/mpd.conf
    src: ./mpd/mpd.conf
    link: link

  mycli:
    dst: ~/.myclirc
    src: ./mycli/.myclirc
    link: link

  ncmpcpp:
    dst: ~/.config/ncmpcpp/config
    src: ./ncmpcpp/config
    link: link

  neofetch:
    dst: ~/.config/neofetch/config
    src: ./neofetch/config
    link: link

  neovim:
    dst: ~/.config/nvim/
    src: ./vim/
    instignore:
      - '*templated*'
    link: link_children
  neovim_templated:
    dst: ~/.config/nvim/templated/
    src: ./vim/templated/
  neovim_plug:
    src: ./vim-plug/plug.vim
    dst: ~/.config/nvim/autoload/plug.vim
    link: link
    actions:
     - nvim_plug_install

  npmrc:
    dst: ~/.npmrc
    src: ./npm/.npmrc

  onedrive:
    src: ./onedrive/config
    dst: ~/.config/onedrive/config
    link: link

  openbox:
    dst: ~/.config/openbox/
    src: ./openbox/config/
  openbox_theme:
    dst: ~/.local/share/themes/Arc-Dark/openbox-3/
    src: ./openbox/theme/
    link: link

  pacman_hooks:
    src: ./pacman_hooks/
    dst: /etc/pacman.d/hooks/

  profile_sync_daemon:
    src: ./profile-sync-daemon/psd.conf
    dst: ~/.config/psd/psd.conf
    link: link

  prusa_slicer:
    dst: ~/.config/PrusaSlicer/
    src: ./PrusaSlicer/
    cmpignore:
    - 'cache'
    - 'vendor'
    - 'snapshots'
    upignore:
    - 'cache'
    - 'vendor'
    - 'snapshots'

  pycodestyle:
    dst: ~/.config/pycodestyle
    src: ./pycodestyle/pycodestyle.cfg
    link: link

  pylint:
    dst: ~/.config/pylintrc
    src: ./pylint/pylintrc
    link: link

  ranger:
    dst: ~/.config/ranger/
    src: ./ranger/
    link: link

  redshift:
    dst: ~/.config/redshift.conf
    src: ./redshift/redshift.conf
    link: link

  repetier_cura:
    dst: ~/.local/share/RepetierHost/
    src: ./repetier/cura/
    link: link_children
  repetier_printers:
    dst: ~/.mono/registry/CurrentUser/software/repetier/printer/
    src: ./repetier/printers
    link: link_children

  ripgrep:
    dst: ~/.config/ripgrep/ripgreprc
    src: ./ripgrep/ripgreprc

  rofi:
    dst: ~/.config/rofi
    src: ./rofi
    link: link

  rofimoji:
    dst: ~/.config/rofimoji.rc
    src: ./rofimoji/rofimoji.rc
    link: link

  rofi-pass:
    dst: ~/.config/rofi-pass/config
    src: ./rofi-pass/config
    link: link

  rust-motd:
    dst: ~/.config/rust-motd/config.toml
    src: ./rust-motd/config.toml

  setxkbmap:
    dst: ~/.config/setxkbmap.conf
    src: ./setxkbmap/setxkbmap.conf
    link: link

  sqlite:
    dst: ~/.sqliterc
    src: ./sqlite/.sqliterc
    link: link

  ssh:
    dst: ~/.ssh/config
    src: ./ssh/config.gpg
    trans_read: _gpg
    trans_write: _gpg

  systemd:
    dst: ~/.config/systemd/user/
    src: ./systemd/
    link: link_children

  termite:
    dst: ~/.config/termite/config
    src: ./termite/config

  tern:
    dst: ~/.tern-project
    src: ./tern/.tern-project
    link: link

  thunar:
    dst: ~/.config/Thunar/uca.xml
    src: ./thunar/uca.xml

  tumbler:
    dst: ~/.config/tumbler/tumbler.rc
    src: ./thunar/tumbler.rc
    link: link

  tint2:
    dst: ~/.config/tint2/
    src: ./tint2/

  tmux:
    dst: ~/.tmux.conf
    src: ./tmux/.tmux.conf
    link: link

  tmuxinator-profiles:
    src: ./tmuxinator-profiles/
    dst: ~/.tmuxinator/
    link: link
  tmuxinator-completion:
    src: ./tmuxinator/completion/tmuxinator.zsh
    dst: ~/.oh-my-zsh/custom/plugins/tmuxinator.zsh
    link: link

  vim:
    dst: ~/.vim
    src: ./vim/
    instignore:
      - '*templated*'
    link: link_children
  vim_templated:
    dst: ~/.vim/templated/
    src: ./vim/templated/

  xbindkeys:
    dst: ~/.xbindkeysrc
    src: ./xbindkeys/.xbindkeysrc
    link: link

  xresources:
    dst: ~/.Xresources
    src: ./xresources/.Xresources
    link: link

  yay:
    dst: ~/.config/yay/config.json
    src: ./yay/config.json
    link: link

  zathura:
    dst: ~/.config/zathura/zathurarc
    src: ./zathura/zathurarc
    link: link

  zshrc:
    dst: ~/.zshrc
    src: ./zsh/.zshrc
    link: link
  zsh_custom:
    dst: ~/.oh-my-zsh/custom/
    src: ./zsh/custom/
    actions:
    - oh_my_zsh_install
  zsh_prompt:
    src: ./pure
    dst: ~/.zsh/pure
    link: link
  zsh_async:
    src: ./zsh-async
    dst: ~/.zsh/async
    link: link

profiles:
  neovim:
    dotfiles:
    - neovim
    - neovim_templated
    - neovim_plug

  tmuxinator:
    dotfiles:
    - tmux
    - tmuxinator-completion
    - tmuxinator-profiles

  zsh:
    dotfiles:
    - zshrc
    - zsh_custom
    - zsh_prompt
    - zsh_async

  # Default dotfiles for main computers
  Default:
    include:
    - neovim
    - tmuxinator
    - zsh
    dotfiles:
    - alacritty
    - bin
    - picom
    - check_pacman_packages
    - chktex
    - ctags
    - cron
    - cura
    - cura_machines
    - dunst
    - firefox
    - flake8
    - fontconfig
    - git
    - gtk
    - latex_templates
    - linters
    - mpd
    - mycli
    - ncmpcpp
    - neofetch
    - npmrc
    - onedrive
    - openbox
    - openbox_theme
    - profile_sync_daemon
    # - prusa_slicer
    - pycodestyle
    - pylint
    - ranger
    - redshift
    - repetier_printers
    - repetier_cura
    - ripgrep
    - rofi
    - rofimoji
    - rofi-pass
    - rust-motd
    - setxkbmap
    - sqlite
    - ssh
    - systemd
    - termite
    - tern
    - thunar
    - tumbler
    - tint2
    - tmux
    - vim
    - xbindkeys
    - xresources
    - yay
    - zathura

  root:
    dotfiles:
      - etc
      - interception
      - pacman_hooks

  Zeus:
    include:
    - Default

  Hermes:
    include:
    - Default
    dotfiles:
    - autorandr

  robitaille.host:
    include:
    - neovim
    - zsh
    dotfiles:
    - rust-motd

  marcel-VirtualBox:
    include:
    - neovim
    - zsh
    dotfiles:
    - alacritty
    - bin
    - ctags
    - flake8
    - setxkbmap
    - sqlite
    - tern
    - tmux
    - xbindkeys
    - xresources
