actions:
  pre:
    vim-plug-install: test -e ~/.vim/autoload/plug.vim || (mkdir -p ~/.vim/autoload; curl
      -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  vim-plug: vim +PlugInstall +qall
dynvariables:
  mozilla_path: find ~/.mozilla/firefox -name '*.default'
config:
  backup: true
  banner: true
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:

  # Alacritty
  alacritty.yml:
    dst: ~/.config/alacritty/alacritty.yml
    src: ./alacritty/alacritty.yml

  # Autorandr
  postswitch:
    dst: ~/.config/autorandr/postswitch
    src: ./autorandr/postswitch
    link: true

  # Bin
  bin:
    dst: ~/bin/
    src: ./bin/
    link: true

  # Compton
  compton.conf:
    dst: ~/.config/compton/compton.conf
    src: ./compton/compton.conf
    link: true

  # Ctags
  ctags:
    dst: ~/.ctags
    src: ./ctags/.ctags
    link: true

  # Dunst
  dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: ./dunst/dunstrc
    link: true
  dunst_icons:
    dst: ~/.icons/dunst/
    src: ./dunst/icons/
    link: true

  # Firefox
  firefox:
    dst: "{{@@ mozilla_path @@}}"
    src: ./firefox/

  # Git
  gitconfig:
    dst: ~/.config/git/config
    src: ./git/.gitconfig
    link: true

  # GTK
  gtk:
    dst: ~/.config/gtk-3.0/
    src: ./gtk/
    link: true

  # Lead
  lead:
    dst: ~/.config/lead/lead.conf
    src: ./lead/lead.conf
    link: true

  # Linters
  linters:
    dst: ~/
    src: ./linters/

  # MPD
  mpd:
    dst: ~/.config/mpd/mpd.conf
    src: ./mpd/mpd.conf
    link: true

  # MyCLI
  myclirc:
    dst: ~/.myclirc
    src: ./mycli/.myclirc
    link: true

  # ncmpcpp
  ncmpcpp:
    dst: ~/.config/ncmpcpp/config
    src: ./ncmpcpp/config
    link: true

  # neofetch
  neofetch:
    dst: ~/.config/neofetch/config
    src: ./neofetch/config
    link: true

  # NPM
  npmrc:
    dst: ~/.npmrc
    src: ./npm/.npmrc
    link: true

  # openbox
  openbox:
    dst: ~/.config/openbox/
    src: ./openbox/config/
    link: true
  openbox_theme:
    dst: ~/.local/share/themes/Arc-Dark/openbox-3/
    src: ./openbox/theme/
    link: true

  # Ranger
  ranger:
    dst: ~/.config/ranger/
    src: ./ranger/
    link: true

  # Redshift
  redshift:
    dst: ~/.config/redshift.conf
    src: ./redshift/redshift.conf
    link: true

  # Rofi pass
  rofi-pass:
    dst: ~/.config/rofi-pass/config
    src: ./rofi-pass/config
    link: true

  # setxkbmap
  setxkbmap:
    dst: ~/.config/setxkbmap.conf
    src: ./setxkbmap/setxkbmap.conf
    link: true

  # sxhkd
  sxhkdrc:
    dst: ~/.config/sxhkd/sxhkdrc
    src: ./sxhkd/sxhkdrc
    link: true

  # Termite
  termite:
    dst: ~/.config/termite/config
    src: ./termite/config
    link: true

  # Tern
  tern:
    dst: ~/.tern-project
    src: ./tern/.tern-project
    link: true

  # Thunar
  thunar:
    dst: ~/.config/Thunar/uca.xml
    src: ./thunar/uca.xml
    link: true
  tumbler:
    dst: ~/.config/tumbler/tumbler.rc
    src: ./thunar/tumbler.rc
    link: true

  # tint2
  tint2:
    dst: ~/.config/tint2/
    src: ./tint2/

  # tmux
  tmux:
    dst: ~/.tmux.conf
    src: ./tmux/.tmux.conf
    link: true

  # tmuxinator
  tmuxinator:
    dst: ~/.config/tmuxinator/
    src: ./tmuxinator/
    link: true

  vim:
    dst: ~/.vim/
    src: ./vim/
    actions:
     - vim-plug-install
     - vim-plug

  # X
  x:
    dst: ~/
    src: ./X/

  # yay
  yay:
    dst: ~/.config/yay/config.json
    src: ./yay/config.json
    link: true

  # Zathura
  zathura:
    dst: ~/.config/zathura/zathurarc
    src: ./zathura/zathurarc
    link: true

  # zsh
  zshrc:
    dst: ~/.oh-my-zsh/
    src: ./zsh/
    link: true

profiles:
  Zeus:
    dotfiles:
    - alacritty.yml
    - bin
    - compton.conf
    - ctags
    - dunstrc
    - dunst_icons
    - firefox
    - gitconfig
    - gtk
    - lead
    - linters
    - mpd
    - myclirc
    - ncmpcpp
    - neofetch
    - npmrc
    - openbox
    - openbox_theme
    - ranger
    - redshift
    - rofi-pass
    - setxkbmap
    - sxhkdrc
    - termite
    - tern
    - thunar
    - tumbler
    - tint2
    - tmux
    - tmuxinator
    - vim
    - x
    - yay
    - zathura
    - zshrc
  Hermes:
    dotfiles:
    - alacritty.yml
    - postswitch
    - bin
    - compton.conf
    - ctags
    - dunstrc
    - dunst_icons
    - firefox
    - gitconfig
    - gtk
    - lead
    - linters
    - mpd
    - myclirc
    - ncmpcpp
    - neofetch
    - npmrc
    - openbox
    - openbox_theme
    - ranger
    - redshift
    - rofi-pass
    - setxkbmap
    - sxhkdrc
    - termite
    - tern
    - thunar
    - tumbler
    - tint2
    - tmux
    - tmuxinator
    - vim
    - x
    - yay
    - zathura
    - zshrc

