actions:
  pre:
    vim-plug-install: test -e ~/.vim/autoload/plug.vim || (mkdir -p ~/.vim/autoload; curl
      -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
    # spaceship-install: test -e {{ env['ZSH_CUSTOM'] }}/themes/spaceship-prompt/spaceship.zsh-theme ||
    #   (git clone https://github.com/denysdovhan/spaceship-prompt.git {{ env['ZSH_CUSTOM'] }}/themes/spaceship-prompt;
    #   ln -s {{ env['ZSH_CUSTOM'] }}/themes/spaceship-prompt/spaceship.zsh-theme {{ env['ZSH_CUSTOM'] }}/themes/spaceship.zsh-theme)
    oh-my-zsh-install: test -e ~/.oh-my-zsh/oh-my-zsh.sh || (rm -rf ~/.oh-my-zsh; sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)")
    spaceship-install: test -e ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme ||
      (git clone https://github.com/denysdovhan/spaceship-prompt.git ~/.oh-my-zsh/custom/themes/spaceship-prompt;
      ln -s ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme)
    tmuxinator-completion: test -e ~/.oh-my-zsh/custom/plugins/tmuxinator.zsh ||
      (git clone https://github.com/tmuxinator/tmuxinator.git /tmp/tmuxinator;
      mkdir -p ~/.oh-my-zsh/custom/plugins;
      cp /tmp/tmuxinator/completion/tmuxinator.zsh ~/.oh-my-zsh/custom/plugins/)
  vim-plug: vim +PlugInstall +qall
variables:
  color_background: '12181e'
  color_foreground: 'FFFFFD'
  color_text: '000000'
  color_cursor: 'ffffff'
  color_normal_black: '12181e'
  color_normal_red: 'ad4117'
  color_normal_green: '659b45'
  color_normal_yellow: 'b8cc4b'
  color_normal_blue: '3a74bc'
  color_normal_magenta: 'bdcb92'
  color_normal_cyan: '96744A'
  color_normal_white: 'e3e2e1'
  color_bright_black: '5b7083'
  color_bright_red: 'f6f2b9'
  color_bright_green: '8d9fba'
  color_bright_yellow: '7fd84b'
  color_bright_blue: 'e6c675'
  color_bright_magenta: 'e7ff5f'
  color_bright_cyan: 'd19851'
  color_bright_white: 'fffffd'
  color_dim_black: '333333'
  color_dim_red: 'f2777a'
  color_dim_green: '99cc99'
  color_dim_yellow: 'ffcc66'
  color_dim_blue: '6699cc'
  color_dim_magenta: 'cc99cc'
  color_dim_cyan: '66cccc'
  color_dim_white: 'dddddd'

  standard_ignored_folders:
    - '.git'
    - '.pioenvs'
    - '.piolibdeps'
    - 'env'
    - 'venv'
    - 'build'
    - 'public'
    - 'static'
    - 'vendor'
    - 'htmlcov'
    - 'node_modules'
    - '__pycache__'
    - 'jest-coverage'
    - 'static'
    - 'static.debug'
    - 'migrations'

  standard_ignored_files:
    - 'tags'
    - '*.swp'
    - 'yarn.*'
    - '*.zip'
    - 'package-lock.json'

dynvariables:
  mozilla_path: find ~/.mozilla/firefox -name '*.default'
config:
  backup: true
  banner: true
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:

  # Alacritty
  alacritty.yml:
    dst: ~/.config/alacritty/alacritty.yml
    src: ./alacritty/alacritty.yml

  # Autorandr
  postswitch:
    dst: ~/.config/autorandr/postswitch
    src: ./autorandr/postswitch
    link: link

  # Bin
  bin:
    dst: ~/bin/
    src: ./bin/

  # Compton
  compton.conf:
    dst: ~/.config/compton/compton.conf
    src: ./compton/compton.conf
    link: link

  # Ctags
  ctags:
    dst: ~/.ctags
    src: ./ctags/.ctags
    link: link

  cura:
    dst: ~/.config/cura/4.0/cura.cfg
    src: ./cura/cura.cfg
    link: link

  # Dunst
  dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: ./dunst/dunstrc
    link: link
  dunst_icons:
    dst: ~/.icons/dunst/
    src: ./dunst/icons/
    link: link

  # Firefox
  firefox:
    dst: "{{@@ mozilla_path @@}}"
    src: ./firefox/

  # Flake 8 python linter
  flake8:
    dst: ~/.config/flake8
    src: ./flake8/flake8
    link: link

  # Git
  gitconfig:
    dst: ~/.config/git/config
    src: ./git/.gitconfig
    link: link

  # GTK
  gtk:
    dst: ~/.config/gtk-3.0/
    src: ./gtk/
    link: link

  # Lead
  lead:
    dst: ~/.config/lead/lead.conf
    src: ./lead/lead.conf
    link: link

  # Linters
  linters:
    dst: ~/
    src: ./linters/
    link: link_children

  # MPD
  mpd:
    dst: ~/.config/mpd/mpd.conf
    src: ./mpd/mpd.conf
    link: link

  # MyCLI
  myclirc:
    dst: ~/.myclirc
    src: ./mycli/.myclirc
    link: link

  # ncmpcpp
  ncmpcpp:
    dst: ~/.config/ncmpcpp/config
    src: ./ncmpcpp/config
    link: link

  # neofetch
  neofetch:
    dst: ~/.config/neofetch/config
    src: ./neofetch/config
    link: link

  # NPM
  npmrc:
    dst: ~/.npmrc
    src: ./npm/.npmrc
    link: link

  # openbox
  openbox:
    dst: ~/.config/openbox/
    src: ./openbox/config/
    link: link
  openbox_theme:
    dst: ~/.local/share/themes/Arc-Dark/openbox-3/
    src: ./openbox/theme/

  # Ranger
  ranger:
    dst: ~/.config/ranger/
    src: ./ranger/
    link: link

  # Redshift
  redshift:
    dst: ~/.config/redshift.conf
    src: ./redshift/redshift.conf
    link: link

  repetier_cura:
    dst: ~/.local/share/RepetierHost/
    src: ./repetier/cura/
    link: link_children
  repetier_printers:
    dst: ~/.mono/registry/CurrentUser/software/repetier/printer/
    src: ./repetier/printers
    link: link_children

  # Rofi pass
  rofi-pass:
    dst: ~/.config/rofi-pass/config
    src: ./rofi-pass/config
    link: link

  # setxkbmap
  setxkbmap:
    dst: ~/.config/setxkbmap.conf
    src: ./setxkbmap/setxkbmap.conf
    link: link

  # sqlite
  sqliterc:
    dst: ~/.sqliterc
    src: ./sqlite/.sqliterc
    link: link

  # sxhkd
  sxhkdrc:
    dst: ~/.config/sxhkd/sxhkdrc
    src: ./sxhkd/sxhkdrc
    link: link

  # Termite
  termite:
    dst: ~/.config/termite/config
    src: ./termite/config

  # Tern
  tern:
    dst: ~/.tern-project
    src: ./tern/.tern-project
    link: link

  # Thunar
  thunar:
    dst: ~/.config/Thunar/uca.xml
    src: ./thunar/uca.xml
    link: link
  tumbler:
    dst: ~/.config/tumbler/tumbler.rc
    src: ./thunar/tumbler.rc
    link: link

  # tint2
  tint2:
    dst: ~/.config/tint2/
    src: ./tint2/

  # tmux
  tmux:
    dst: ~/.tmux.conf
    src: ./tmux/.tmux.conf
    link: link

  # tmuxinator
  tmuxinator:
    dst: ~/.tmuxinator/
    src: ./tmuxinator/
    link: link

  vim:
    dst: ~/.vim/
    src: ./vim/
    actions:
     - vim-plug-install
     - vim-plug
    link: link_children

  # X
  x:
    dst: ~/
    src: ./X/
    link: link_children

  # yay
  yay:
    dst: ~/.config/yay/config.json
    src: ./yay/config.json
    link: link

  # Zathura
  zathura:
    dst: ~/.config/zathura/zathurarc
    src: ./zathura/zathurarc
    link: link

  # zsh
  zshrc:
    dst: ~/.zshrc
    src: ./zsh/.zshrc
    link: link
  zsh_custom:
    dst: ~/.oh-my-zsh/custom/
    src: ./zsh/custom/
    actions:
    - oh-my-zsh-install
    - spaceship-install
    - tmuxinator-completion

profiles:
  Zeus:
    dotfiles:
    - alacritty.yml
    - bin
    - compton.conf
    - ctags
    - dunstrc
    - dunst_icons
    - firefox
    - flake8
    - gitconfig
    - gtk
    - lead
    - linters
    - mpd
    - myclirc
    - ncmpcpp
    - neofetch
    - npmrc
    - openbox
    - openbox_theme
    - ranger
    - redshift
    - repetier_printers
    - repetier_cura
    - rofi-pass
    - setxkbmap
    - sxhkdrc
    - termite
    - tern
    - thunar
    - tumbler
    - tint2
    - tmux
    - tmuxinator
    - vim
    - x
    - yay
    - zathura
    - zshrc
    - zsh_custom
  Hermes:
    dotfiles:
    - alacritty.yml
    - postswitch
    - bin
    - compton.conf
    - ctags
    - dunstrc
    - dunst_icons
    - firefox
    - flake8
    - gitconfig
    - gtk
    - lead
    - linters
    - mpd
    - myclirc
    - ncmpcpp
    - neofetch
    - npmrc
    - openbox
    - openbox_theme
    - ranger
    - redshift
    - rofi-pass
    - setxkbmap
    - sxhkdrc
    - termite
    - tern
    - thunar
    - tumbler
    - tint2
    - tmux
    - tmuxinator
    - vim
    - x
    - yay
    - zathura
    - zshrc
    - zsh_custom
  marcel-VirtualBox:
    dotfiles:
    - vim
    - zshrc
    - zsh_custom
    - tmux
    - x
    - alacritty.yml
    - setxkbmap
    - ctags
    - bin
    - tern
    - sqliterc
    - tmuxinator
    - flake8
